<a href="https://colab.research.google.com/github/kithulovali/MachineLearning-Ai/blob/main/numpy_serries.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

arr = np.array(
    [[[1,2,3,4,5,6,7,8,9],
     [1,2,3,4,5,6,7,8,9],
     [1,2,3,4,5,6,7,8,9]]])
print(arr)
#print(type(arr))
print(arr.ndim) # dimesion size

[[[1 2 3 4 5 6 7 8 9]
  [1 2 3 4 5 6 7 8 9]
  [1 2 3 4 5 6 7 8 9]]]
<class 'numpy.ndarray'>
3
