In [11]:
import numpy as np 
myarr = np.arange(10)
myarr


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# copying and array into another one 

arr = np.array([1,3,4,5,56,78,90])
print(arr)
arr1 = arr.copy()
arr1[0]=28
print(arr1)

In [22]:
# view() and copy() methods
arr = np.array([2,4,5,6,7,8,9,10,11,20,24])
arr1 = arr.view()
arr2 = arr.copy()
arr1[0]= 45
arr2[0]= 56
print(arr) 
print(arr1)
print(arr2)

[45  4  5  6  7  8  9 10 11 20 24]
[45  4  5  6  7  8  9 10 11 20 24]
[56  4  5  6  7  8  9 10 11 20 24]
