In [21]:
import numpy as np 
from numpy import random 
arr1 = random.randint(100 , size=5)
print(arr1)


[40 98 67 63 24]


In [13]:
import numpy as np
from numpy import random
# randomise array1
arr1 = random.randint(100 ,size=(12))
print(arr1)
# randomise array 2 
arr2 = random.randint(10 , size=(12))
print(arr2)
# array addition 
arr3 = np.add(arr1,arr2)
# array subtraction
arr4 = np.subtract(arr1,arr2)
# array multiplication
arr5 = np.multiply(arr1,arr2)
# array division
arr6 = np.divide(arr1,arr2)
print("devision :",arr6)
print("multiplication :",arr5)
print("subtruction :",arr4)
print("sum :",arr3)

[ 4 72 42 10 51 23 70 67 10 81  2 89]
[7 2 8 4 7 0 1 3 0 2 8 9]
devision : [ 0.57142857 36.          5.25        2.5         7.28571429         inf
 70.         22.33333333         inf 40.5         0.25        9.88888889]
multiplication : [ 28 144 336  40 357   0  70 201   0 162  16 801]
subtruction : [-3 70 34  6 44 23 69 64 10 79 -6 80]
sum : [11 74 50 14 58 23 71 70 10 83 10 98]


C:\Users\danbash\AppData\Local\Temp\ipykernel_1876\3512893290.py:16: RuntimeWarning: divide by zero encountered in divide
  arr6 = np.divide(arr1,arr2)


In [15]:
arr2 = random.randint(100, size=5)
print(arr2)

[96 25 58 98 83]


In [23]:
arr3 = np.prod([arr1,arr2])
print(arr3)

449630811592704000


In [ ]:
# sum of an array

In [30]:
# array 1 generation
array1 = random.randint(100 , size=10)
print(array1)
# array 2 generation
array2 = random.randint(100 , size= 10)
print(array2)
# array sum 
print(np.sum([array1,array2]))

[19 33 86 87 85 55 64 88 29 20]
[29 95 28 24 84 79 18 94 36 71]
1124
