In [11]:
import numpy as np 
myarr = np.arange(10)
myarr


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
import numpy as np
# array shapes() 
arr = np.array([[11,12,13,14,15],[22,23,24,25,26]])
sh = arr.shape
print(sh)

(2, 5)


In [15]:
arr = np.array([1,2,3,4,5,6,7,8,9])
print(arr.shape)

(1, 9)


In [47]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16])
arr3D = arr.reshape(2,2,4)
print(arr3D)
for i in np.nditer(arr3D):
 print(i)

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]]
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
