In [11]:
import numpy as np 
myarr = np.arange(10)
myarr


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# copying and array into another one 

arr = np.array([1,3,4,5,56,78,90])
print(arr)
arr1 = arr.copy()
arr1[0]=28
print(arr1)

In [22]:
# view() and copy() methods
arr = np.array([2,4,5,6,7,8,9,10,11,20,24])
arr1 = arr.view()
arr2 = arr.copy()
arr1[0]= 45
arr2[0]= 56
print(arr) 
print(arr1)
print(arr2)

[45  4  5  6  7  8  9 10 11 20 24]
[45  4  5  6  7  8  9 10 11 20 24]
[56  4  5  6  7  8  9 10 11 20 24]


In [8]:
import numpy as np
# array shapes() 
arr = np.array([[11,12,13,14,15],[22,23,24,25,26]])
sh = arr.shape
print(sh)

(2, 5)


In [15]:
arr = np.array([1,2,3,4,5,6,7,8,9])
print(arr.shape)

(1, 9)


In [25]:
#arr = np.array(1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20)
# reshape from  1D to 2D
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])
newarr2 = arr.reshape(2,10)
# reshape from 1D to 3D
newarr3 = arr.reshape(2,2,5)
print(newarr)
print(newarr3)

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]]
[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[11 12 13 14 15]
  [16 17 18 19 20]]]
