In [2]:
"""
Exercise 1
Create a 1-D NumPy array containing numbers from 1 to 10.
"""
import numpy as np
arr = np.arange(10)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [9]:
"""
Exercise 2
Create a 2×3 NumPy array filled with zeros.
"""
from numpy import random 
arr = random.randint(1 ,size=(2,5))
print(arr)

[[0 0 0 0 0]
 [0 0 0 0 0]]


In [20]:
"""
Exercise 3
Create a 3×3 array filled with  zeros and ones.
"""
arr = random.randint(2 ,size=(3,3))
print(arr)

[[1 1 0]
 [0 0 0]
 [1 0 0]]


In [23]:
"""
Exercise 4
Create an array of 5 equally spaced numbers between 0 and 1.
"""
arr = random.rand(5)
print(arr)


[0.86160533 0.39362749 0.33918782 0.63530235 0.26567826]


In [26]:
"""
Exercise 5
Create a NumPy array from the Python list:
"""
plist = [4, 7, 10, 13, 16] 
nlist = np.array(plist)
print(plist)

[4, 7, 10, 13, 16]
