In [1]:

import numpy as np 
from numpy import random

In [6]:
"""
Exercise 6

Create the following NumPy array:
[[1, 2, 3],
 [4, 5, 6]]

Then print:
The shape of the array
The data type of the array
The number of dimensions
"""
arr = np.array([[1,2,3],[4,5,6]])
print(arr)
print(arr.ndim) # printing dimensions
print(arr.shape) # printing the shape
print(arr.dtype) # printing the datatype

[[1 2 3]
 [4 5 6]]
2
(2, 3)
int64


In [28]:
from numpy import random
"""
Create a one-dimensional NumPy array containing 12 elements.
Then:
Reshape the array into a 3×4 matrix
Print the reshaped array
Print the new shape of the array
"""
arr = random.randint(100, size=(12))
print(arr.ndim)
Rarr = arr.reshape(3,4)
print(arr)
print(Rarr)
print(Rarr.shape)

1
[ 7 83 20 13 45 49 89 23 96 72 16  3]
[[ 7 83 20 13]
 [45 49 89 23]
 [96 72 16  3]]
(3, 4)


In [29]:
"""
"""

_IncompleteInputError: incomplete input (969763094.py, line 1)